collection: umich-protest-pilot-02
workers: 1
generateWACZ: true
limit: 20

seeds:
  - url: https://record.umich.edu
    scopeType: domain
    exclude:
      - ".*\\/topics\\/.*"
      - ".*\\/category\\/.*"
      - ".*\\/tag\\/.*"

  - url: https://president.umich.edu
    scopeType: prefix